

spring.datasource.url=jdbc:postgresql://<host>:5432/<dbname>
spring.datasource.username=<dbname_jlmq_user>
spring.datasource.password=<xyWzjTuagopCH99kSDvNpLLZUWlT8TrN>

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
