server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d7eab49kh4rs73a8oo9g-a:5432/dbname_jlmq
spring.datasource.username=dbname_jlmq_user
spring.datasource.password=xyWzjTuagopCH99kSDvNpLLZUWlT8TrN

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
